# Reusable composite action for roam-code analysis.
# Usage in other repos:
#   - uses: Cranot/roam-code@main
#     with:
#       command: 'fitness'
#       comment: 'true'

name: 'Roam Code Analysis'
description: 'Run roam-code analysis on your codebase with PR comments and SARIF upload'
branding:
  icon: 'search'
  color: 'blue'

inputs:
  command:
    description: 'Roam command to run (e.g., "preflight --staged", "fitness", "pr-risk")'
    required: false
    default: 'fitness'
  python-version:
    description: 'Python version'
    required: false
    default: '3.12'
  comment:
    description: 'Post results as PR comment'
    required: false
    default: 'true'
  fail-on-violation:
    description: 'Fail the build on violations (non-zero exit code)'
    required: false
    default: 'false'
  roam-version:
    description: 'Specific roam-code version (empty for latest)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # -- Python setup --------------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # -- Install roam-code ---------------------------------------------------
    - name: Install roam-code
      shell: bash
      run: |
        if [ -n "${{ inputs.roam-version }}" ]; then
          pip install "roam-code==${{ inputs.roam-version }}"
        else
          pip install roam-code
        fi

    # -- Index the repo so all commands have data to work with ---------------
    - name: Index codebase
      shell: bash
      run: roam index --root .

    # -- Run the requested analysis command ----------------------------------
    - name: Run analysis
      id: analysis
      shell: bash
      run: |
        set +e
        OUTPUT=$(roam --json ${{ inputs.command }} --root . 2>&1)
        EXIT_CODE=$?
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        echo "$OUTPUT" > roam-output.json
        set -e
        if [ "${{ inputs.fail-on-violation }}" = "true" ] && [ $EXIT_CODE -ne 0 ]; then
          echo "::error::Roam analysis found violations"
          exit 1
        fi

    # -- Post (or update) a PR comment with the results ----------------------
    - name: Post PR comment
      if: inputs.comment == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let output;
          try {
            output = JSON.parse(fs.readFileSync('roam-output.json', 'utf8'));
          } catch(e) {
            output = { summary: fs.readFileSync('roam-output.json', 'utf8') };
          }

          const summary = output.summary || 'Analysis complete';
          const command = '${{ inputs.command }}';

          const body = [
            '## Roam Code Analysis',
            '',
            `**Command:** \`roam ${command}\``,
            `**Summary:** ${typeof summary === 'string' ? summary : JSON.stringify(summary)}`,
            '',
            '<details><summary>Full output</summary>',
            '',
            '```json',
            JSON.stringify(output, null, 2).substring(0, 60000),
            '```',
            '',
            '</details>',
            '',
            '---',
            '*Generated by [roam-code](https://github.com/Cranot/roam-code)*'
          ].join('\n');

          // Find and update existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const existing = comments.find(c => c.body.includes('## Roam Code Analysis'));
          if (existing) {
            await github.rest.issues.updateComment({
              comment_id: existing.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            });
          }
